### ISSUE TITLE
Error running on ESP32 as is. Any idea what should be changed?

### ISSUE THREAD

**Issue by johruss** [anson-vandoren/esp8266-captive-portal#10]
Starting captive portal
Waiting for access point to turn on
AP mode configured: ('192.168.4.1', '255.255.255.0', '192.168.4.1', '192.168.4.1')
HTTP Server listening on ('0.0.0.0', 80)
Configured HTTP server
DNS Server listening on ('0.0.0.0', 53)
Configured DNS server
Sending www.gstatic.com. -> 192.168.4.1
Sending www.google.com. -> 192.168.4.1
Sending www.gstatic.com. -> 192.168.4.1
- Accepting new HTTP connection
Sending www.google.com. -> 192.168.4.1
Sending www.gstatic.com. -> 192.168.4.1
- Reading incoming HTTP data
- Accepting new HTTP connection
Sending www.youtube.com. -> 192.168.4.1
- Sending outgoing HTTP data
Sending ssl.gstatic.com. -> 192.168.4.1
- Reading incoming HTTP data
- Accepting new HTTP connection
Sending www.gstatic.com. -> 192.168.4.1
- Sending outgoing HTTP data
- Accepting new HTTP connection
Sending www.google.com. -> 192.168.4.1
- Reading incoming HTTP data
Sending spclient.wg.spotify.com. -> 192.168.4.1
- Sending outgoing HTTP data
- Reading incoming HTTP data
- Accepting new HTTP connection
Sending mtalk.google.com. -> 192.168.4.1
- Sending outgoing HTTP data
Sending dealer.spotify.com. -> 192.168.4.1
- Reading incoming HTTP data
Sending dealer.spotify.com. -> 192.168.4.1
- Sending outgoing HTTP data
Sending 0.client-channel.google.com. -> 192.168.4.1
- Sending outgoing HTTP data
Sending signaler-pa.clients6.google.com. -> 192.168.4.1
- Sending outgoing HTTP data
Sending clients4.google.com. -> 192.168.4.1
- Sending outgoing HTTP data
Sending oauthaccountmanager.googleapis.com. -> 192.168.4.1
Sending favrohdoy. -> 192.168.4.1
- Accepting new HTTP connection
Sending yuxjawivfx. -> 192.168.4.1
- Accepting new HTTP connection
Sending yqncsolbleyg. -> 192.168.4.1
- Reading incoming HTTP data
- Accepting new HTTP connection
- Sending outgoing HTTP data
- Accepting new HTTP connection
Sending calendar.google.com. -> 192.168.4.1
- Reading incoming HTTP data
- Reading incoming HTTP data
- Reading incoming HTTP data
- Sending outgoing HTTP data
- Sending outgoing HTTP data
- Sending outgoing HTTP data
- Sending outgoing HTTP data
- Accepting new HTTP connection
- Sending outgoing HTTP data
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "captive_portal.py", line 168, in start
  File "captive_portal.py", line 125, in captive_portal
  File "captive_portal.py", line 147, in handle_http
  File "captive_http.py", line 223, in write_to
OSError: [Errno 104] ECONNRESET

**Comment by anson-vandoren** [comment]
@johruss sorry for taking so long to get back to you on this. The issue is unlikely related to ESP32 vs ESP8266, and I just ran this successfully on a ESP32-WROOM-32 dev board. 

Based on the stack trace you provided, it looks like the client (your phone, or whatever other device you were using to connect to the ESP32 captive portal) closed the TCP socket while the ESP32 was still trying to communicate. Not a bug in the code here, but an error condition that I don't have handled. The reason for the client resetting the socket is unrelated to this code, but catching (and ignoring) reset sockets might let you proceed anyway.

I'll submit a patch in a few minutes for this.

Anson
